# Generated by Django 6.0.6 on 2026-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='director_email',
            field=models.EmailField(default='directivo@safetrack.local', max_length=254),
        ),
        migrations.AddField(
            model_name='inspection',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='inspection_evidence/'),
        ),
    ]
