# Generated by Django 6.0.6 on 2026-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commerce_director_email_inspection_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='director_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='director_feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
