# Generated by Django 6.0.6 on 2026-06-05 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inspection_director_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestControlProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=40)),
                ('service_area', models.CharField(max_length=140)),
                ('certified', models.BooleanField(default=True)),
                ('certification_expiration', models.DateField(blank=True, null=True)),
                ('price_level', models.CharField(choices=[('economico', 'Economico'), ('medio', 'Medio'), ('premium', 'Premium')], default='medio', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, default=19.432608, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=-99.133209, max_digits=9)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanitationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('instructions', models.TextField()),
                ('assigned_to', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('employee_notes', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='task_evidence/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_feedback', models.TextField(blank=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.commerce')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('option_a', models.CharField(max_length=160)),
                ('option_b', models.CharField(max_length=160)),
                ('option_c', models.CharField(max_length=160)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.trainingcourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attempts', to='app.commerce')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.trainingcourse')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.trainingcourse')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
