# Generated by Django 6.0.6 on 2026-06-05 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pestcontrolprovider_trainingcourse_sanitationtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('monthly_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('has_courses', models.BooleanField(default=False)),
                ('max_employees', models.PositiveIntegerField(default=10)),
                ('highlighted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Empleado', max_length=80)),
                ('area', models.CharField(default='Cocina', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.commerce')),
            ],
        ),
    ]
