# Generated by Django 6.0.6 on 2026-06-05 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subscriptionplan_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='task_evidence/photos/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_photos', to='app.sanitationtask')),
            ],
        ),
    ]
