# Generated by Django 6.0.6 on 2026-06-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_taskevidencephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseattempt',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_attempts', to='app.employee'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='app.employee'),
        ),
        migrations.AddField(
            model_name='sanitationtask',
            name='assigned_to_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='app.employee'),
        ),
        migrations.AddField(
            model_name='sanitationtask',
            name='frequency',
            field=models.CharField(choices=[('once', 'Una vez'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseattempt',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sanitationtask',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
