# Generated by Django 6.0.6 on 2026-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_courseattempt_employee_inspection_inspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link de YouTube o Vimeo', null=True),
        ),
    ]
